# -*- coding: utf-8 -*-
"""Taller_ Portafolio_ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCTh5zn_wm2wAmgJEsgi1WGMy8tN-YZQ

# 📘 Taller Evaluativo (20%) - Análisis de Portafolio
### Curso: Ingeniería Financiera / Programación  
### Herramienta: Google Colab  

1.   Elemento de la lista
2.   Elemento de la lista


---
### 🎯 Objetivo
Este taller busca que comprendas qué es un análisis de portafolio, cómo se calculan y analizan sus métricas (rentabilidad, riesgo y correlación), y cómo se interpreta el resultado para tomar decisiones de inversión.

👉 **Importante:** No basta con ejecutar el código. Debes **completar los espacios en blanco**, responder las **preguntas de investigación** y redactar un **análisis final**.

## 1. Importación de librerías
Primero, importa las librerías necesarias para trabajar con datos financieros.
"""

# COMPLETAR: importa las librerias necesarias (yfinance, pandas, numpy, matplotlib, seaborn)
# Ejemplo: import yfinance as yf

# COMPLETAR AQUI

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## 2. Descarga de datos

*   Elemento de la lista
*   Elemento de la lista


Usa `yfinance` para descargar los precios de **Google (GOOG)**, **Amazon (AMZN)** y **Microsoft (MSFT)** durante los últimos 3 años. Utiliza la columna `Adj Close`.

🔎 **Pregunta:** ¿Por qué es más adecuado usar `Adj Close` que `Close` para un análisis financiero?
"""

# COMPLETAR: descarga los precios de las acciones usando yf.download

acciones = ["GOOG", "AMZN", "MSFT"]
datos = yf.download(tickers=acciones)["Close"]
datos.head()

datos.tail() # Veo los ultimos 5 datos

"""## 3. Visualización de precios
Grafica en una misma figura la evolución de los precios de cierre ajustados de las tres acciones.

🔎 **Pregunta:** ¿Cuál de las tres acciones muestra mayor crecimiento en estos 3 años?
"""

# COMPLETAR: grafica de las tres series de precios en una sola gráfica

plt.figure(figsize=(10, 6))
plt.plot(datos["GOOG"], label="GOOG")
plt.plot(datos["AMZN"], label="AMZN")
plt.plot(datos["MSFT"], label="MSFT")
plt.legend()
plt.show()

import plotly.express as px

datos.px
plt.show()

"""## 4. Rentabilidades
Calcula las **rentabilidades logarítmicas diarias** y grafícalas.

🔎 **Pregunta:** ¿Qué diferencias encuentras entre observar precios y observar rentabilidades?
"""

# COMPLETAR: calcula los rendimientos logarítmicos

rendimientos = np.log(datos / datos.shift(1))
rendimientos = rendimientos.dropna()
(rendimientos.head())

# Graficar
# COMPLETAR AQUÍ

# COMPLETAR: graficar los rendimientos logaritmicos diarios

plt.figure(figsize=(11, 6))

for c in rendimientos.columns:
    plt.plot(rendimientos.index, rendimientos[c], label=c)

plt.title("Rentabilidades logartitmicas diarias")
plt.xlabel("fecha")
plt.ylabel("retorno diario")
plt.legend()
plt.show()

"""### Análisis

- Cuando observamos **precios**, vemos una tendencia general, es decir, crecen o decrecen en el tiempo.
- En cambio, al observar **rentabilidades**, vemos la variacion diaria (subidas y bajadas alrededor de 0).

## 5. Medidas estadísticas
Calcula la **rentabilidad promedio** y la **volatilidad (desviación estándar)** de cada acción.

🔎 **Pregunta:** ¿Cuál acción es más riesgosa? ¿Cuál ofrece mayor retorno?
"""

# COMPLETAR: calcula media y desviación estándar

media = rendimientos.mean()
volatilidad = volatilidad = rendimientos.std()

print("Rentabilidad promedio diaria:")
print(media)
print("\nVolatilidad diaria:")
print(volatilidad)

"""### Análisis Punto 5

- La acción con mayor **rentabilidad promedio** es la más rentable.  
- La acción con mayor **volatilidad** es la más riesgosa.  
- Generalmente, a mayor rentabilidad esperada también se asume un mayor riesgo.

## 6. Correlación entre activos
Calcula y grafica la matriz de correlación entre las acciones.

🔎 **Pregunta:** ¿Qué significa que dos acciones tengan una correlación cercana a 1? ¿Y cercana a 0 o negativa?
"""

# COMPLETAR: calcula la correlación y haz un mapa de calor con seaborn

correlacion = rendimientos.corr()

sns.heatmap(correlacion, annot=True, cmap="coolwarm")
plt.title("matriz de correlacion entre acciones")
plt.show()

print("Matriz de correlación:")
print(correlacion)

"""### Análisis Punto 6

- Una correlación cercana a **1** significa que dos acciones tienden a moverse en la misma dirección.  
- Una correlación cercana a **0** indica que no existe una relación clara entre ellas.  
- Una correlación **negativa** significa que los activos se mueven en direcciones opuestas, lo cual es útil para diversificación.  

En este caso, observamos que:
- El par más correlacionado es ____ (ejemplo: GOOG y MSFT).  
- El par menos correlacionado es ____ (ejemplo: AMZN y MSFT).  

Esto muestra que las acciones tienen una relación positiva, aunque no perfecta, lo que permite cierta reducción de riesgo al diversificar.
"""



"""## 7. Portafolio simulado
Supón un portafolio con la siguiente distribución:
- 40% Google
- 30% Amazon
- 30% Microsoft

Calcula el **retorno esperado** y la **volatilidad del portafolio**.

🔎 **Preguntas:**
1. ¿Cómo interpretas el retorno esperado del portafolio?
2. ¿Qué efecto tuvo la diversificación sobre la volatilidad respecto a invertir en una sola acción?
"""

# COMPLETAR: cálculo del retorno y riesgo del portafolio

pesos = np.array([0.4, 0.3, 0.3])

retorno_portafolio = np.dot(pesos, rendimientos.mean())
covarianza = rendimientos.cov()
vol_portafolio = np.sqrt(np.dot(pesos.T, np.dot(covarianza, pesos)))

print("Retorno esperado del portafolio (diario):", retorno_portafolio)
print("Volatilidad del portafolio (diaria):", vol_portafolio)

"""### Análisis Punto 7

- El **retorno esperado del portafolio** es el promedio ponderado de las rentabilidades de las tres acciones según los pesos definidos.  
- La **volatilidad del portafolio** representa el riesgo total de la inversión considerando tanto el riesgo individual de cada acción como sus correlaciones.  
- En general, la diversificación permite que la volatilidad del portafolio sea **menor** que la de la acción más riesgosa de manera individual.  
- Esto significa que repartir la inversión entre varias acciones ayuda a reducir el riesgo sin sacrificar demasiado retorno.

✍️ 8. Conclusión final
Redacta un análisis completo del portafolio respondiendo:

¿Qué acción fue más rentable y cuál más riesgosa?
¿Qué tan correlacionadas están las acciones?
¿Qué aportó la diversificación al portafolio?
Si fueras un inversionista, ¿invertirías en este portafolio? Justifica tu respuesta.

### Conclusión Final

- **Acción más rentable:** fue aquella con mayor rentabilidad promedio (según los resultados del Punto 5).  
- **Acción más riesgosa:** fue la que presentó la mayor volatilidad (según el Punto 5).  
- **Correlación entre acciones:** en el Punto 6 vimos que las correlaciones fueron positivas, lo que significa que las acciones tienden a moverse en la misma dirección, aunque no perfectamente.  
- **Diversificación:** gracias a la combinación (40% GOOG, 30% AMZN y 30% MSFT), la volatilidad del portafolio fue menor que la de la acción más riesgosa por separado. Esto muestra que la diversificación reduce el riesgo sin perder demasiado retorno.  
- **Decisión de inversión:** sí consideraría invertir en este portafolio, ya que ofrece un balance entre rentabilidad y riesgo. Sin embargo, como inversionista también tendría en cuenta factores externos como la situación del mercado, noticias sobre cada empresa y mi tolerancia personal al riesgo.
"""